# Generated by Django 4.1.2 on 2022-10-27 10:23

from django.db import migrations, models
import store.validator


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/media", validators=[store.validator.validate_file_size]
            ),
        ),
    ]
