# Generated by Django 4.1.1 on 2022-09-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_customer_store_custo_last_na_2e448d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_last_na_2e448d_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
