# Generated by Django 4.1.1 on 2022-09-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_customer_store_custo_last_na_2e448d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
    ]
