# Generated by Django 4.1.1 on 2022-09-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_product_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="selling_price",
        ),
    ]
