# Generated by Django 4.1.1 on 2022-09-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_product_selling_price"),
    ]

    operations = []
