# Generated by Django 4.1.1 on 2022-09-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_auto_20220910_0018"),
    ]

    operations = []
