# Generated by Django 4.1.1 on 2022-09-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_auto_20220910_0019"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=255),
        ),
    ]
